strassengezwitscher/events/models.py, strassengezwitscher/events/tests/test_models.py, strassengezwitscher/facebook/models.py, strassengezwitscher/facebook/tests/test_models.py, strassengezwitscher/mapobjects/admin.py, strassengezwitscher/mapobjects/models.py, strassengezwitscher/mapobjects/tests.py, strassengezwitscher/mapobjects/tests/test_models.py, strassengezwitscher/mapobjects/views.py, strassengezwitscher/strassengezwitscher/settings.py, strassengezwitscher/strassengezwitscher/tests.py, strassengezwitscher/strassengezwitscher/wsgi.py
für Matze...
@piepmatz über den `localsettings` import meckert er auch. Gibt es da eine schönere Lösung?
Dass die beiden ungenutzten Dateien rausfliegen, ist optional.
=> Improve coverage and health

strassengezwitscher/strassengezwitscher/settings.py
=> Disable browsable API of rest framework in production mode.

.coveragerc, gulpfile.js
=> Improve coverage report

strassengezwitscher/strassengezwitscher/settings/default.py, strassengezwitscher/strassengezwitscher/urls.py, strassengezwitscher/templates/admin.html, strassengezwitscher/users/apps.py, strassengezwitscher/users/fixtures/users_views_testdata.json, strassengezwitscher/users/templates/users/detail.html, strassengezwitscher/users/templates/users/form.html, strassengezwitscher/users/templates/users/list.html, strassengezwitscher/users/tests/test_views.py, strassengezwitscher/users/urls.py, strassengezwitscher/users/views.py
- List users.
- Create users.
- Update users.
Fixes #71 #72
=> Add pages for user management.

e2e/test_contact.js, frontend/contact.component.html, frontend/contact.component.scss, frontend/contact.component.spec.ts, frontend/contact.component.ts, frontend/contact.service.ts, frontend/contact.ts, frontend/main.ts, gulp.config.js, package.json, systemjs.config.js
=> Issue 58/frontend contact form

crowdgezwitscher/static/css/frontend.css, crowdgezwitscher/templates/frontend.html
=> Loading page for user area

gulpfile.js
=> Improve exit codes in gulp file.

crowdgezwitscher/crowdgezwitscher/views.py, crowdgezwitscher/templates/admin.html, crowdgezwitscher/templates/dashboard.html
=> Add dashboard for internal area.

crowdgezwitscher/templates/admin.html, crowdgezwitscher/templates/frontend.html
=> Issue 148/html scripts

crowdgezwitscher/crowdgezwitscher/tests/test_views.py, crowdgezwitscher/crowdgezwitscher/urls.py, e2e/test_app.js, frontend/app/app.component.html, frontend/app/app.component.scss, frontend/app/app.module.ts, frontend/app/app.routing.ts, frontend/app/imprint/imprint.component.html, frontend/app/imprint/imprint.component.ts, frontend/app/imprint/index.ts, gulp.config.js, package.json, systemjs.config.js
Vorschlag für #187 
@mathebox könntest du mal drüber schauen und Feedback geben ob die Anordnung des "Links" in den Stil reinpasst, würde dass dann entsprechend für die anderen beiden Links (Über uns #188  und Spenden #181)  analog machen
=> Add Imprint Page in Userfrontend

crowdgezwitscher/crowdgezwitscher/tests/test_views.py, crowdgezwitscher/crowdgezwitscher/urls.py, e2e/test_app.js, frontend/app/about/about.component.html, frontend/app/about/about.component.ts, frontend/app/about/index.ts, frontend/app/app.component.html, frontend/app/app.component.scss, frontend/app/app.module.ts, frontend/app/app.routing.ts, gulp.config.js, systemjs.config.js
Solves #188 .
Der genaue Text muss dann vor Veröffentlichung noch hinzugefügt werden.
Bzw. kann jederzeit ins in die app.component.html eingefügt werden.
=> Added about page to userfrontend

frontend/app/map/map.component.scss
=> Fix CSS for info cards on map.

e2e/test_app.js, frontend/app/app.component.html, frontend/app/app.component.scss
=> added donation link to the userfrontend

e2e/test_app.js, frontend/app/app.component.html, frontend/app/app.component.scss
- Hide links depending on screen size.
Fixes #210
=> Make toolbar menu more responsive.

frontend/app/map/map.component.html, frontend/app/map/map.component.ts
Fixes #241 
Ich musste den Text etwas kürzen.
Es gibt leider noch einen Bug in Angular-Material, der nur erlaubt die Tooltips unter dem Element anzuzeigen.
=> Add info text to map filter (via tooltip).

crowdgezwitscher/crowdgezwitscher/tests/test_views.py, crowdgezwitscher/crowdgezwitscher/urls.py, e2e/test_app.js, frontend/app/app.component.html, frontend/app/app.module.ts, frontend/app/app.routing.ts, frontend/app/blog/blog.component.html, frontend/app/blog/blog.component.scss, frontend/app/blog/blog.component.ts, frontend/app/blog/index.ts, gulp.config.js, systemjs.config.js
Fixes #239 
Ich find das Design noch nicht überragend, aber mir ist fällt nichts besseres ein.
=> Add static blog.

frontend/app/map/map.component.html
=> Fix mapObject-checkbox-without-filters-bug

frontend/app/events/event/event.component.html, frontend/app/events/event/event.component.ts, frontend/app/events/shared/event.ts, frontend/app/helper.ts
=> Zeigt Datum für Veranstaltungen in regional üblichem Format

crowdgezwitscher/events/templates/events/list.html
=> Hinzufügen von ID, Ort, Datum zur Veranstaltungsliste im Betreiberbereich

frontend/app/map/map.component.html, frontend/app/map/map.component.spec.ts, frontend/app/map/map.component.ts
=> Fixes bug that requests events initally multiple times

crowdgezwitscher/users/templates/users/form.html, crowdgezwitscher/users/views.py
=> Use selectizejs for user groups input.

frontend/app/contact/contact.component.spec.ts, frontend/app/contact/contact.component.ts
=> Issue 280/fix-contactForm-bugs

e2e/test_contact.js, frontend/app/contact/contact.component.html, frontend/app/contact/contact.component.ts, frontend/app/contact/contact.service.ts
fixes #271 
Enable fileupload in Firefox & Correct submit using XMLHttpRequest in Firefox
=> Issue 271/contact form firefox support

crowdgezwitscher/crowdgezwitscher/widgets.py, crowdgezwitscher/events/templates/events/form.html, crowdgezwitscher/events/views.py, gulp.config.js, package.json
=> Show datepicker for date inputs.

crowdgezwitscher/events/fixtures/events_views_testdata.json, crowdgezwitscher/events/serializers.py, crowdgezwitscher/events/tests/test_api_views.py, frontend/app/events/event/event.component.html
Fixes #294. Funktionalität im Frontend war schon implementiert. Nur die API hat die Daten nicht mit ausgegeben.
=> Shows organizer in user frontend.

frontend/app/events/eventDetail/eventDetail.component.html, frontend/app/events/eventDetail/eventDetail.component.scss, frontend/app/events/eventDetail/eventDetail.component.spec.ts, frontend/app/events/eventDetail/eventDetail.component.ts
=> Show message if twitter is blocked

crowdgezwitscher/blog/tests/test_views.py, crowdgezwitscher/events/tests/test_views.py, crowdgezwitscher/facebook/tests/test_views.py, crowdgezwitscher/users/tests/test_views.py
=> Test views with explicit user permissions.

frontend/app/events/event/event.component.html, frontend/app/events/event/event.component.scss, frontend/app/events/event/event.component.ts, frontend/app/events/eventDetail/eventDetail.component.ts, frontend/app/facebook/facebookPage.component.html, frontend/app/facebook/facebookPage.component.scss, frontend/app/facebook/facebookPage.component.ts, frontend/app/facebook/facebookPage.module.ts, frontend/app/map/map.component.html, frontend/app/map/map.component.spec.ts, frontend/app/map/map.component.ts
=> closing button for infobox

frontend/app/contact/contact.component.spec.ts, frontend/app/events/event/event.component.spec.ts, frontend/app/events/eventDetail/eventDetail.component.spec.ts, frontend/app/events/shared/event.service.spec.ts, frontend/app/facebook/facebookPage.component.spec.ts, frontend/app/facebook/facebookPage.service.spec.ts
=> added more typescript tests

crowdgezwitscher/users/templates/users/detail.html, crowdgezwitscher/users/templates/users/form.html, crowdgezwitscher/users/views.py
=> Add bootstrap design to user form.

frontend/app/map/map.component.ts, frontend/app/map/map.service.spec.ts, frontend/app/map/map.service.ts
Hab es mit Beispieldaten lokal getestet, hat funktioniert.
=> Fixes #350

frontend/app/events/eventDetail/eventDetail.component.html, frontend/app/events/eventDetail/eventDetail.component.scss
=> Keep formatting of  event notes in user area.

crowdgezwitscher/base/widgets.py
=> Fix time input widget.

crowdgezwitscher/facebook/forms.py, crowdgezwitscher/facebook/models.py, crowdgezwitscher/facebook/templates/facebook/detail.html, crowdgezwitscher/facebook/templates/facebook/form.html, crowdgezwitscher/facebook/views.py
- Add button to facebook page.
- Put facebook page form in separate file.
Fixes #200 
PS: ja dieses Eingabefeld gab es nicht
=> Add input field for facebook id.

crowdgezwitscher/base/widgets.py, crowdgezwitscher/blog/forms.py, crowdgezwitscher/blog/models.py, crowdgezwitscher/blog/templates/blog/form.html, crowdgezwitscher/blog/templates/blog/list.html, crowdgezwitscher/blog/tests/test_views.py, crowdgezwitscher/blog/views.py, crowdgezwitscher/events/tests/test_views.py
- Improve list view.
- Improve form view.
- Some cleanup.
=> Improve blog app.

crowdgezwitscher/blog/urls_api.py, crowdgezwitscher/blog/views.py, crowdgezwitscher/blog/views_api.py, crowdgezwitscher/events/urls_api.py, crowdgezwitscher/events/views.py, crowdgezwitscher/events/views_api.py, crowdgezwitscher/facebook/urls_api.py, crowdgezwitscher/facebook/views.py, crowdgezwitscher/facebook/views_api.py
Fixes #110 
Bessere Code-Separation, analog zu `urls.py` und `urls_api.py`
=> Move api views to separate files.

crowdgezwitscher/base/forms.py, crowdgezwitscher/base/templates/admin.html, crowdgezwitscher/base/templates/change_password.html, crowdgezwitscher/base/tests/test_views.py, crowdgezwitscher/base/views.py, crowdgezwitscher/crowdgezwitscher/urls.py
=> Add password change form for users

frontend/app/map/map.component.ts, frontend/app/map/map.service.spec.ts, frontend/app/map/map.service.ts
Fixes #369 
**Note**
should not be merged before 2018-01-01
=> Add 2018 to map event filter

frontend/app/map/map.component.html, frontend/app/map/map.component.scss, frontend/app/map/map.component.ts, frontend/app/map/mapObject.model.ts, frontend/app/map/mapObjectCreation/mapObjectCreation.component.html, frontend/app/map/mapObjectCreation/mapObjectCreation.component.ts
This should fixes request changes to the display of adding new events, removing a step in between.
Also provides a work-around for browser, who do not cope with datetime-local properly.
=> Fixes add map objects

crowdgezwitscher/twitter/tests/test_utils.py, crowdgezwitscher/twitter/utils.py
=> Delete lock file if no PID can be read.

crowdgezwitscher/twitter/utils.py
=> Use fixed path for lock file.

crowdgezwitscher/base/templates/frontend.html, crowdgezwitscher/base/templates/landingpage.html, frontend/app/blog/blog.component.html, frontend/app/contact/contact.component.html, frontend/app/imprint/imprint.component.html, gulp.config.js, package.json
Bitte zum testen in develop mergen
=> Änderungen Juli 2018 

crowdgezwitscher/events/urls_api.py, crowdgezwitscher/events/views_api.py, frontend/app/map/map.component.html, frontend/app/map/map.component.spec.ts, frontend/app/map/map.component.ts, frontend/app/map/map.service.spec.ts, frontend/app/map/map.service.ts, package-lock.json, tsconfig.json
Dynamically adds years to filter the map
=> Add current years
